language: csharp
dotnet: 3.1
solution: SendGrid.sln
os: linux
dist: bionic
mono: none
services:
- docker
script:
- make test-docker
- make release
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push **/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
    --skip-duplicate
  on:
    branch: main
    tags: true
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: gAocxB0AUjYq7Kd5v5W2dWbvKPiMTXNQWL5WE9tSxIZPtWF4jrjtWZGNvKhQgGz4pkzqHd0h+O24eg6PoVRx1f1AiQ4sVUZGyRzDQJV5EhvSqPbJoh4NPnTDSxZTA35GaUE2xuN4iyoUdAHM+I5JX4QzW6/OCPyetor1T4X0x50=
